### ISSUE TITLE
scan报错

### ISSUE THREAD

**Issue by scopion** [madneal/gshark#128]
root@security:/opt/gshark/server# ./gshark scan
您正在使用config的默认值,config的路径为config.yaml
/opt/gshark/server <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8abd18]

goroutine 1 [running]:
gorm.io/gorm.(*DB).getInstance(0x10?)
	/root/go/pkg/mod/gorm.io/gorm@v1.20.9/gorm.go:306 +0x18
gorm.io/gorm.(*DB).Where(0xf96d19?, {0xe39400, 0x1152300}, {0xc0003a3ab0, 0x1, 0x1})
	/root/go/pkg/mod/gorm.io/gorm@v1.20.9/chainable_api.go:142 +0x3c
github.com/madneal/gshark/service.GetValidRulesByType({0xf96d19, 0x6})
	/opt/gshark/server/service/rule.go:55 +0xa5
github.com/madneal/gshark/search/githubsearch.RunTask(0x384)
	/opt/gshark/server/search/githubsearch/search.go:103 +0x3f
github.com/madneal/gshark/search.Scan(0xc0003a6180?)
	/opt/gshark/server/search/scan.go:56 +0x178
github.com/urfave/cli/v2.(*Command).Run(0x2be7680, 0xc0003a6140)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5dc
github.com/urfave/cli/v2.(*App).RunContext(0xc000097860, {0x115e380?, 0xc0000c2028}, {0xc0000be000, 0x2, 0x2})
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb7d
github.com/urfave/cli/v2.(*App).Run(...)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/opt/gshark/server/main.go:28 +0x407

使用release里边的报错，使用自己编译出来的也报错。
Ubuntu系统，华为云。

**Comment by scopion** [comment]
库的权限没给用户。。。
