### ISSUE TITLE
windows搭建报错，请问该如何解决呢

### ISSUE THREAD

**Issue by liangzai-ff** [madneal/gshark#220]
C:\Users\Administrator\Desktop\gshark_windows_amd64>gshark.exe web   
您正在使用config的默认值,config的路径为config.yaml
panic: Fatal error configFilename file: open config.yaml: The system cannot find the file specified. 

goroutine 1 [running]:
github.com/madneal/gshark/core.Viper({0x0, 0x0, 0xc000054000?})
        /home/runner/work/gshark/gshark/server/core/viper.go:40 +0x617
main.main()
        /home/runner/work/gshark/gshark/server/main.go:11 +0x1e

**Comment by liangzai-ff** [comment]
未修改config-temp.yaml 至config.yaml导致
